[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.7"
fixed = "1.24.0"
memmap2 = "0.9.3"
mimalloc = "0.1.39"
rayon = "1.8.0"
